version: '3.8'

services:
  # Frontend React Application only
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: boe-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api/v1
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: boe-network
    external: true