"""Make fields secure by default

Revision ID: b6ba69b48173
Revises: fa1f44df8e58
Create Date: 2025-08-08 17:23:42.430218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ba69b48173'
down_revision: Union[str, None] = 'fa1f44df8e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update NULL values to False to preserve existing behavior
    op.execute("UPDATE fields SET is_restricted = false WHERE is_restricted IS NULL")
    
    # Then make the column NOT NULL with default=true for new fields
    op.alter_column('fields', 'is_restricted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fields', 'is_restricted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
