"""Add field-level RBAC columns

Revision ID: fa1f44df8e58
Revises: fc4759068d14
Create Date: 2025-08-08 17:05:17.001024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1f44df8e58'
down_revision: Union[str, None] = 'fc4759068d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benchmarks')
    op.drop_table('funds')
    op.drop_table('fund_time_series')
    op.drop_table('transactions')
    op.add_column('fields', sa.Column('required_role', sa.String(length=50), nullable=True))
    op.add_column('fields', sa.Column('required_permissions', sa.JSON(), nullable=True))
    op.add_column('fields', sa.Column('is_restricted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'is_restricted')
    op.drop_column('fields', 'required_permissions')
    op.drop_column('fields', 'required_role')
    op.create_table('transactions',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('transaction_id', name='transactions_pkey')
    )
    op.create_table('fund_time_series',
    sa.Column('fund_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('nav', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('return_1d', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('aum', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fund_id', 'date', name='fund_time_series_pkey')
    )
    op.create_table('funds',
    sa.Column('fund_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fund_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fund_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inception_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('manager', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fund_id', name='funds_pkey')
    )
    op.create_table('benchmarks',
    sa.Column('benchmark_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('benchmark_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('benchmark_id', name='benchmarks_pkey')
    )
    # ### end Alembic commands ###
